from __future__ import annotations

import json
import os
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import yaml


# ============================================================
# PATHS AND SETTINGS
# ============================================================

ROOT = Path(
    os.environ.get(
        "OFFMAP_ROOT",
        Path(__file__).resolve().parents[1],
    )
).resolve()

INDEX_PATH = ROOT / "data" / "opportunities.json"
CONFIG_PATH = ROOT / "config" / "categories.yml"
OPPORTUNITIES_DIR = ROOT / "opportunities"

GENERATED_MARKER = (
    "<!-- OFFMAP GENERATED CATEGORY PAGE\n"
    "Do not edit manually. Generated by scripts/build_category_pages.py.\n"
    "-->"
)

EXPECTED_INDEX_SCHEMA_VERSION = 2
EXPECTED_INDEX_RECORD_TYPE = "opportunity-index"
EXPECTED_CONFIG_SCHEMA_VERSION = 1
PREVIEW_LIMIT = 10
CLOSING_SOON_DAYS = 14
MAX_CELL_ITEMS = 3


# ============================================================
# ERRORS AND BASIC HELPERS
# ============================================================

def fail(message: str) -> None:
    print(f"::error::{message}")
    raise SystemExit(1)


def warn(message: str) -> None:
    print(f"::warning::{message}")


def clean(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    if not isinstance(value, str):
        return None
    result = " ".join(value.split())
    return result or None


def nested(record: dict[str, Any], *keys: str) -> Any:
    value: Any = record
    for key in keys:
        if not isinstance(value, dict):
            return None
        value = value.get(key)
    return value


def require_mapping(
    value: Any,
    *,
    context: str,
) -> dict[str, Any]:
    if not isinstance(value, dict):
        fail(f"{context} must be a YAML/JSON object.")
    return value


def require_string(
    value: Any,
    *,
    context: str,
) -> str:
    result = clean(value)
    if result is None:
        fail(f"{context} must contain text.")
    return result


def require_string_list(
    value: Any,
    *,
    context: str,
) -> list[str]:
    if not isinstance(value, list):
        fail(f"{context} must be a list.")
    result: list[str] = []
    for index, item in enumerate(value):
        result.append(
            require_string(
                item,
                context=f"{context}[{index}]",
            )
        )
    return result


def humanize(value: str) -> str:
    return (
        value.replace("-", " ")
        .replace("_", " ")
        .title()
    )


def unique_strings(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []

    result: list[str] = []
    seen: set[str] = set()

    for item in value:
        text = clean(item)
        if text is None:
            continue
        key = text.casefold()
        if key in seen:
            continue
        seen.add(key)
        result.append(text)

    return result


def parse_iso_date(value: Any) -> date | None:
    text = clean(value)
    if text is None:
        return None

    try:
        parsed = datetime.strptime(text, "%Y-%m-%d").date()
    except ValueError:
        return None

    if parsed.isoformat() != text:
        return None

    return parsed


def markdown_text(
    value: Any,
    fallback: str = "Not confirmed",
) -> str:
    text = clean(value) or fallback
    return (
        text.replace("\\", "\\\\")
        .replace("|", "\\|")
        .replace("[", "\\[")
        .replace("]", "\\]")
        .replace("\n", " ")
    )


def markdown_link(label: str, target: str) -> str:
    safe_label = markdown_text(label, fallback="Link")
    return f"[{safe_label}](<{target}>)"


def relative_link(
    from_page: Path,
    target: Path,
    *,
    directory: bool = False,
) -> str:
    relative = os.path.relpath(
        target,
        start=from_page.parent,
    )
    value = Path(relative).as_posix()
    if directory and not value.endswith("/"):
        value += "/"
    return value


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


# ============================================================
# CONFIGURATION
# ============================================================

def load_config() -> tuple[
    list[str],
    dict[str, dict[str, Any]],
]:
    if not CONFIG_PATH.is_file():
        fail(
            f"Missing category configuration: "
            f"{CONFIG_PATH.relative_to(ROOT)}"
        )

    try:
        payload = yaml.safe_load(
            CONFIG_PATH.read_text(encoding="utf-8")
        )
    except (OSError, yaml.YAMLError) as exc:
        fail(f"Could not read category configuration: {exc}")

    config = require_mapping(
        payload,
        context="Category configuration",
    )

    if config.get("schema_version") != EXPECTED_CONFIG_SCHEMA_VERSION:
        fail(
            "config/categories.yml must use "
            f"schema_version {EXPECTED_CONFIG_SCHEMA_VERSION}."
        )

    navigation = require_string_list(
        config.get("navigation"),
        context="config.navigation",
    )

    if len(set(navigation)) != len(navigation):
        fail("config.navigation contains duplicate categories.")

    raw_main_categories = require_mapping(
        config.get("main_categories"),
        context="config.main_categories",
    )

    main_categories: dict[str, dict[str, Any]] = {}

    for main_key in navigation:
        raw_main = require_mapping(
            raw_main_categories.get(main_key),
            context=f"config.main_categories.{main_key}",
        )

        title = require_string(
            raw_main.get("title"),
            context=f"{main_key}.title",
        )
        emoji = require_string(
            raw_main.get("emoji"),
            context=f"{main_key}.emoji",
        )
        description = require_string(
            raw_main.get("description"),
            context=f"{main_key}.description",
        )
        raw_categories = require_mapping(
            raw_main.get("categories"),
            context=f"{main_key}.categories",
        )

        categories: dict[str, dict[str, str]] = {}
        used_routes: set[str] = set()

        for category_key, raw_category_value in raw_categories.items():
            category_key = require_string(
                category_key,
                context=f"{main_key} category key",
            )
            raw_category = require_mapping(
                raw_category_value,
                context=(
                    f"config.main_categories.{main_key}."
                    f"categories.{category_key}"
                ),
            )

            category_title = require_string(
                raw_category.get("title"),
                context=f"{main_key}.{category_key}.title",
            )
            category_emoji = require_string(
                raw_category.get("emoji"),
                context=f"{main_key}.{category_key}.emoji",
            )
            route = require_string(
                raw_category.get("route"),
                context=f"{main_key}.{category_key}.route",
            )
            category_description = require_string(
                raw_category.get("description"),
                context=f"{main_key}.{category_key}.description",
            )

            if "/" in route or route in {".", ".."}:
                fail(
                    f"{main_key}.{category_key}.route must be "
                    "one safe folder name."
                )

            if route in used_routes:
                fail(
                    f"{main_key} contains duplicate route "
                    f"'{route}'."
                )
            used_routes.add(route)

            categories[category_key] = {
                "title": category_title,
                "emoji": category_emoji,
                "route": route,
                "description": category_description,
            }

        main_categories[main_key] = {
            "title": title,
            "emoji": emoji,
            "description": description,
            "categories": categories,
        }

    return navigation, main_categories


# ============================================================
# CENTRAL OPPORTUNITY INDEX
# ============================================================

def load_index() -> list[dict[str, Any]]:
    if not INDEX_PATH.is_file():
        fail(
            f"Missing central opportunity index: "
            f"{INDEX_PATH.relative_to(ROOT)}. "
            "Run scripts/build_indexes.py first."
        )

    try:
        payload = json.loads(
            INDEX_PATH.read_text(encoding="utf-8")
        )
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"Could not read the central opportunity index: {exc}")

    index = require_mapping(
        payload,
        context="Opportunity index",
    )

    if index.get("schema_version") != EXPECTED_INDEX_SCHEMA_VERSION:
        fail(
            "data/opportunities.json must use "
            f"schema_version {EXPECTED_INDEX_SCHEMA_VERSION}."
        )

    if index.get("record_type") != EXPECTED_INDEX_RECORD_TYPE:
        fail(
            "data/opportunities.json must have "
            "record_type 'opportunity-index'."
        )

    opportunities = index.get("opportunities")
    if not isinstance(opportunities, list):
        fail("data/opportunities.json opportunities must be a list.")

    records: list[dict[str, Any]] = []

    for index_number, item in enumerate(opportunities):
        if not isinstance(item, dict):
            fail(
                "data/opportunities.json opportunity "
                f"#{index_number + 1} must be an object."
            )

        if clean(item.get("status")) != "published":
            warn(
                "Ignoring an indexed record whose status is not "
                f"published: {item.get('title', 'Untitled')}"
            )
            continue

        records.append(item)

    return records


# ============================================================
# ACTIVE RECORDS AND SORTING
# ============================================================

def is_rolling(record: dict[str, Any]) -> bool:
    candidates = (
        nested(
            record,
            "dates",
            "application_deadline",
            "raw",
        ),
        nested(
            record,
            "dates",
            "application_deadline",
            "display",
        ),
    )

    return any(
        "rolling" in text.casefold()
        for value in candidates
        if (text := clean(value)) is not None
    )


def normalized_deadline(
    record: dict[str, Any],
) -> date | None:
    return parse_iso_date(
        nested(
            record,
            "dates",
            "application_deadline",
            "normalized",
        )
    )


def is_active(
    record: dict[str, Any],
    *,
    today: date,
) -> bool:
    if is_rolling(record):
        return True

    deadline = normalized_deadline(record)
    if deadline is None:
        return True

    return deadline >= today


def deadline_sort_key(
    record: dict[str, Any],
) -> tuple[int, date, str]:
    deadline = normalized_deadline(record)
    title = (
        clean(record.get("title"))
        or "Untitled Opportunity"
    ).casefold()

    if deadline is not None:
        return (0, deadline, title)

    if is_rolling(record):
        return (1, date.max, title)

    return (2, date.max, title)


def group_active_records(
    records: list[dict[str, Any]],
    *,
    navigation: list[str],
    main_categories: dict[str, dict[str, Any]],
    today: date,
) -> dict[str, dict[str, list[dict[str, Any]]]]:
    grouped: dict[
        str,
        dict[str, list[dict[str, Any]]],
    ] = {
        main_key: {
            category_key: []
            for category_key in main_categories[
                main_key
            ]["categories"]
        }
        for main_key in navigation
    }

    ignored_counts: dict[str, int] = {}

    for record in records:
        main_key = clean(record.get("main_category"))
        category_key = clean(record.get("category"))

        if main_key not in grouped:
            ignored_key = main_key or "missing-main-category"
            ignored_counts[ignored_key] = (
                ignored_counts.get(ignored_key, 0) + 1
            )
            continue

        if category_key not in grouped[main_key]:
            fail(
                f"Published record "
                f"'{record.get('title', 'Untitled')}' uses "
                f"category '{category_key}' under '{main_key}', "
                "but config/categories.yml does not define that pair."
            )

        if not is_active(record, today=today):
            continue

        grouped[main_key][category_key].append(record)

    for main_key in navigation:
        for category_key in grouped[main_key]:
            grouped[main_key][category_key].sort(
                key=deadline_sort_key
            )

    for ignored_key, count in sorted(ignored_counts.items()):
        warn(
            f"Ignoring {count} published record(s) from "
            f"non-browsed main category '{ignored_key}'."
        )

    return grouped


# ============================================================
# TABLE DISPLAY
# ============================================================

def display_deadline(record: dict[str, Any]) -> str:
    return (
        clean(
            nested(
                record,
                "dates",
                "application_deadline",
                "display",
            )
        )
        or clean(
            nested(
                record,
                "dates",
                "application_deadline",
                "normalized",
            )
        )
        or clean(
            nested(
                record,
                "dates",
                "application_deadline",
                "raw",
            )
        )
        or "Not confirmed"
    )


def display_status(
    record: dict[str, Any],
    *,
    today: date,
) -> str:
    if is_rolling(record):
        return "ð **ROLLING**"

    deadline = normalized_deadline(record)
    if deadline is None:
        return "â ï¸ **VERIFY**"

    days_remaining = (deadline - today).days
    if days_remaining <= CLOSING_SOON_DAYS:
        return "ð¥ **CLOSING SOON**"

    return "â **OPEN**"


def first_date_text(
    value: Any,
) -> str | None:
    if not isinstance(value, dict):
        return None

    return (
        clean(value.get("display"))
        or clean(value.get("normalized"))
        or clean(value.get("raw"))
    )


def display_program_dates(record: dict[str, Any]) -> str:
    start = first_date_text(
        nested(record, "dates", "start_date")
    )
    end = first_date_text(
        nested(record, "dates", "end_date")
    )

    if start and end and start != end:
        return f"{start} â {end}"
    if start:
        return start
    if end:
        return end
    return "Dates not confirmed"


def display_location(record: dict[str, Any]) -> str:
    display = clean(nested(record, "location", "display"))
    if display:
        return display

    city = clean(nested(record, "location", "host_city"))
    country = clean(
        nested(record, "location", "host_country")
    )
    combined = ", ".join(
        value for value in (city, country) if value
    )
    if combined:
        return combined

    if clean(record.get("format")) == "online":
        return "Online"

    return "Location not confirmed"


def display_when_where(record: dict[str, Any]) -> str:
    return (
        f"{markdown_text(display_program_dates(record))}"
        "<br>"
        f"{markdown_text(display_location(record))}"
    )


def display_focus(record: dict[str, Any]) -> str:
    fields = unique_strings(
        nested(record, "filters", "academic_fields")
    )
    subjects = unique_strings(
        nested(record, "filters", "subjects")
    )
    topics = unique_strings(
        nested(record, "filters", "topics")
    )

    selected = fields[:2] or subjects[:2] or topics[:2]

    if not selected:
        return "Open / multidisciplinary"

    return ", ".join(
        markdown_text(humanize(item))
        for item in selected[:MAX_CELL_ITEMS]
    )


def display_funding(record: dict[str, Any]) -> str:
    features = unique_strings(
        nested(record, "filters", "funding_features")
    )

    if not features:
        return "Not confirmed"

    return ", ".join(
        markdown_text(humanize(item))
        for item in features[:MAX_CELL_ITEMS]
    )


def display_eligibility(record: dict[str, Any]) -> str:
    levels = unique_strings(
        nested(record, "filters", "academic_levels")
    )
    regions = unique_strings(
        nested(record, "filters", "eligible_regions")
    )
    audiences = unique_strings(
        nested(record, "filters", "audience_groups")
    )

    selected = (
        levels[:2]
        + regions[:1]
        + audiences[:1]
    )

    if not selected:
        return "See opportunity page"

    return ", ".join(
        markdown_text(humanize(item))
        for item in selected[:MAX_CELL_ITEMS]
    )


def safe_external_url(value: Any) -> str | None:
    text = clean(value)
    if text is None:
        return None

    parsed = urlparse(text)
    if parsed.scheme not in {"http", "https"}:
        return None
    if not parsed.hostname:
        return None

    return text


def application_link(record: dict[str, Any]) -> str:
    application_url = safe_external_url(
        nested(
            record,
            "application",
            "application_page",
        )
    )
    official_url = safe_external_url(
        nested(
            record,
            "application",
            "official_page",
        )
    )

    if application_url:
        return markdown_link("Apply", application_url)
    if official_url:
        return markdown_link(
            "Official page",
            official_url,
        )

    return "Not confirmed"


def opportunity_link(
    record: dict[str, Any],
    *,
    page_path: Path,
) -> str:
    title = (
        clean(record.get("title"))
        or "Untitled Opportunity"
    )
    path_value = clean(record.get("path"))
    if path_value is None:
        fail(f"Indexed opportunity '{title}' has no path.")

    target = ROOT / path_value
    relative = relative_link(page_path, target)
    return markdown_link(title, relative)


def build_table(
    records: list[dict[str, Any]],
    *,
    page_path: Path,
    category_title: str,
    today: date,
) -> list[str]:
    lines = [
        (
            "| Status | Category | Opportunity | Focus | "
            "When & Where | Format | Funding | Eligibility | "
            "Apply | Deadline |"
        ),
        (
            "|---|---|---|---|---|---|---|---|---|---|"
        ),
    ]

    for record in records:
        opportunity_format = (
            clean(record.get("format"))
            or "not-confirmed"
        )

        cells = [
            display_status(record, today=today),
            markdown_text(category_title),
            opportunity_link(
                record,
                page_path=page_path,
            ),
            display_focus(record),
            display_when_where(record),
            markdown_text(humanize(opportunity_format)),
            display_funding(record),
            display_eligibility(record),
            application_link(record),
            markdown_text(display_deadline(record)),
        ]

        lines.append("| " + " | ".join(cells) + " |")

    return lines


# ============================================================
# PAGE COMPONENTS
# ============================================================

def build_navigation(
    *,
    page_path: Path,
    navigation: list[str],
    main_categories: dict[str, dict[str, Any]],
) -> list[str]:
    home_link = relative_link(
        page_path,
        ROOT / "README.md",
    )
    contributing_link = relative_link(
        page_path,
        ROOT / "CONTRIBUTING.md",
    )

    links = [
        markdown_link("ð  Home", home_link),
        markdown_link("ð¤ Contributing", contributing_link),
    ]

    for main_key in navigation:
        main = main_categories[main_key]
        target = OPPORTUNITIES_DIR / main_key
        route = relative_link(
            page_path,
            target,
            directory=True,
        )
        links.append(
            markdown_link(
                f"{main['emoji']} {main['title']}",
                route,
            )
        )

    midpoint = (len(links) + 1) // 2

    return [
        '<div align="center">',
        "",
        " Â· ".join(links[:midpoint]),
        "",
        " Â· ".join(links[midpoint:]),
        "",
        "</div>",
    ]


def empty_state(category_title: str) -> list[str]:
    submission_url = (
        "https://github.com/elchrysaki/offmap-hub/"
        "issues/new?template=submit-opportunity.yml"
    )

    return [
        (
            f"> No active {category_title.lower()} "
            "have been published yet."
        ),
        ">",
        (
            f"> {markdown_link('Add one to the map â', submission_url)}"
        ),
    ]


def build_main_category_page(
    *,
    main_key: str,
    main: dict[str, Any],
    category_records: dict[
        str,
        list[dict[str, Any]],
    ],
    navigation: list[str],
    main_categories: dict[str, dict[str, Any]],
    today: date,
) -> tuple[Path, str]:
    page_path = (
        OPPORTUNITIES_DIR
        / main_key
        / "README.md"
    )

    total = sum(
        len(records)
        for records in category_records.values()
    )

    lines: list[str] = [
        GENERATED_MARKER,
        "",
        *build_navigation(
            page_path=page_path,
            navigation=navigation,
            main_categories=main_categories,
        ),
        "",
        "---",
        "",
        '<a id="top"></a>',
        "",
        f"# {main['emoji']} {main['title']}",
        "",
        main["description"],
        "",
        (
            f"> **{total} active "
            f"{main['title'].lower()} currently on the map.**"
        ),
        "",
    ]

    for category_key, category in main[
        "categories"
    ].items():
        records = category_records[category_key]
        preview = records[:PREVIEW_LIMIT]

        lines.extend(
            [
                "---",
                "",
                (
                    f"## {category['emoji']} "
                    f"{category['title']}"
                ),
                "",
                category["description"],
                "",
            ]
        )

        if preview:
            lines.extend(
                build_table(
                    preview,
                    page_path=page_path,
                    category_title=category["title"],
                    today=today,
                )
            )
        else:
            lines.extend(
                empty_state(category["title"])
            )

        lines.extend(
            [
                "",
                (
                    "**"
                    + markdown_link(
                        "View all active "
                        + category["title"].lower()
                        + " â",
                        category["route"] + "/",
                    )
                    + "**"
                ),
                "",
                (
                    f"<sub>Showing {len(preview)} of "
                    f"{len(records)} active listings.</sub>"
                    if records
                    else ""
                ),
                "",
                (
                    '<p align="right">'
                    '<a href="#top">â Back to the top</a>'
                    '</p>'
                ),
                "",
            ]
        )

    lines.extend(
        [
            "---",
            "",
            (
                "_Generated from `data/opportunities.json` by "
                "`scripts/build_category_pages.py`. "
                "Always verify details on the official page._"
            ),
            "",
        ]
    )

    return page_path, "\n".join(
        line for line in lines
        if line is not None
    )


def build_full_category_page(
    *,
    main_key: str,
    main: dict[str, Any],
    category_key: str,
    category: dict[str, str],
    records: list[dict[str, Any]],
    navigation: list[str],
    main_categories: dict[str, dict[str, Any]],
    today: date,
) -> tuple[Path, str]:
    page_path = (
        OPPORTUNITIES_DIR
        / main_key
        / category["route"]
        / "README.md"
    )

    back_link = relative_link(
        page_path,
        OPPORTUNITIES_DIR / main_key,
        directory=True,
    )

    lines: list[str] = [
        GENERATED_MARKER,
        "",
        *build_navigation(
            page_path=page_path,
            navigation=navigation,
            main_categories=main_categories,
        ),
        "",
        "---",
        "",
        markdown_link(
            f"â Back to {main['title']}",
            back_link,
        ),
        "",
        (
            f"# {category['emoji']} "
            f"All Active {category['title']}"
        ),
        "",
        category["description"],
        "",
        (
            f"> **{len(records)} active "
            f"{category['title'].lower()} currently on the map.**"
        ),
        "",
    ]

    if records:
        lines.extend(
            build_table(
                records,
                page_path=page_path,
                category_title=category["title"],
                today=today,
            )
        )
    else:
        lines.extend(
            empty_state(category["title"])
        )

    lines.extend(
        [
            "",
            "---",
            "",
            (
                "_This page is generated automatically from the "
                "central OFFMAP opportunity index. "
                "Do not edit its table manually._"
            ),
            "",
        ]
    )

    return page_path, "\n".join(lines)


# ============================================================
# BUILD
# ============================================================

def main() -> None:
    navigation, main_categories = load_config()
    records = load_index()
    today = date.today()

    grouped = group_active_records(
        records,
        navigation=navigation,
        main_categories=main_categories,
        today=today,
    )

    generated_paths: list[Path] = []

    for main_key in navigation:
        main = main_categories[main_key]

        main_page_path, main_page_content = (
            build_main_category_page(
                main_key=main_key,
                main=main,
                category_records=grouped[main_key],
                navigation=navigation,
                main_categories=main_categories,
                today=today,
            )
        )
        atomic_write(
            main_page_path,
            main_page_content,
        )
        generated_paths.append(main_page_path)

        for category_key, category in main[
            "categories"
        ].items():
            page_path, page_content = (
                build_full_category_page(
                    main_key=main_key,
                    main=main,
                    category_key=category_key,
                    category=category,
                    records=grouped[main_key][
                        category_key
                    ],
                    navigation=navigation,
                    main_categories=main_categories,
                    today=today,
                )
            )
            atomic_write(page_path, page_content)
            generated_paths.append(page_path)


if __name__ == "__main__":
    main()
